# Generated by Django 5.0.1 on 2024-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('pub_year', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
